apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-confmap
  namespace: ocp-pj-sample1
data:
  fluent.conf: |
      <source>
        @type tail
        path /logs/defaultServer/verbosegc*.log
        pos_file /var/log/1.log.pos
        tag wlp.verbose1
      </source>

      <match wlp.verbose1>
        @type elasticsearch
        host 172.99.1.218
        port 59200
        user elasticusr
        password Pa$$w0rd
        index_name fluentd.${tag}
        logstash_format true
        logstash_prefix dev.myapp.applogs
        flush_interval 1s
      </match>
